### ISSUE TITLE
Implement support for HED specification's JSON test suite

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-javascript#135]
The HED specification provides a JSON-based test suite at https://github.com/hed-standard/hed-specification/tree/master/tests, which provides a set of example data (including strings, sidecars, TSV files, and combinations thereof), which should pass, and expected errors for those that should fail. This validator should eventually support validating against this test suite in an automated fashion. This would not directly affect the validator's built-in test modules.

The validation could be implemented in two stages:

1. Simple pass-fail validation (without regard to the exact error code).
2. Validating the actual error code.

**Comment by VisLab** [comment]
At this point, #1 is the most important.

**Comment by happy5214** [comment]
This is now done.
