### ISSUE TITLE
Implement or delete converter stub from old-style BIDS schema spec to current spec

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-javascript#137]
The `convertOldSpecToSchemasSpec` function was left unimplemented when support for the current BIDS HED schema specification model was released. It was intended to map the originally proposed format (see https://github.com/hed-standard/hed-specification/issues/156) to the approved spec. Two questions:

1. Does anyone still use the originally proposed model for specifying HED schema versions?
2. Does this function still need to exist?

CC @VisLab

**Comment by VisLab** [comment]
@happy5214 We're going to have to go through this together as I am not sure of the exact differences.  We'll have to evaluate.

**Comment by VisLab** [comment]
This only appeared in a prerelease and was replaced by the current specification upon review by the HED Working Group.
