### ISSUE TITLE
Implement validation for BIDS HED schema version specifications

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-javascript#138]
Currently, there is a stub named `validateSchemaSpec` that was intended to validate schema specifications (i.e. nickname/library/version specs), probably in the already parsed form of `SchemaSpec` objects, but nothing calls it and it currently only does an object type check. What would need to be done to implement this?

**Comment by VisLab** [comment]
I think this might be meant for the implementation of lazy schema loading --- where users can specify an arbitrary number of partnered schemas without prefixes and they are loaded one at a time if no conflicts.  The loader must raise an exception if a conflict occurs and the validation should not proceed.

**Comment by happy5214** [comment]
This stub pre-dates partnered schemas by several months, but it could be repurposed for that. We'll discuss in our meeting.
