### ISSUE TITLE
Events file with BIDS validation issue

### ISSUE THREAD

**Issue by dorahermes** [hed-standard/hed-javascript#182]
I have an issue validating the following _events.tsv BIDS file in the online BIDS validator as it does not correctly detect if I make a typo in the HED column. 
[issue_HEDcolumn_validation.zip](https://github.com/user-attachments/files/16751753/issue_HEDcolumn_validation.zip)

**Comment by happy5214** [comment]
> I have an issue validating the following _events.tsv BIDS file in the online BIDS validator as it does not correctly detect if I make a typo in the HED column. [issue_HEDcolumn_validation.zip](https://github.com/user-attachments/files/16751753/issue_HEDcolumn_validation.zip)

@dorahermes Can you please be more specific? I'm having trouble figuring out what the exact problem is. There don't appear to be any typos in the `HED` column of your example file.

**Comment by happy5214** [comment]
This appears to have been fixed elsewhere. Closing.
