### ISSUE TITLE
Values that are node names

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-javascript#57]
A clarification has been made in the spec that allows values to be node names.  This is in the process of being incorporated into the hed validator.

Definitions are a special case:  Definition names cannot be node names.  However, Definitions can also take values:

`(Definition/My-def/# .... )`     The values substituted for `#` can be node names in `Def/My-def/Red` or `(Def-expand/My-def/Red .... )`

**Comment by happy5214** [comment]
As evidenced by the fact that the test added in 4795a96 had to be skipped in order to be committed, this issue was not fixed in v3.7.0.
