### ISSUE TITLE
Error message when no HEDVersion

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-javascript#90]
The error message when no `HEDVersion` is given in the `dataset_description.json` is not informative:

> Your dataset is not a valid BIDS dataset.
> view 1 error in 1 file
> Error 1: [Code 104] HED_ERROR
> 
> [Click here for more information about this issue](https://neurostars.org/search?q=HED_ERROR)
> The validation on this HED string returned an error.

**Comment by happy5214** [comment]
This is not an issue with this validator. Removing `HEDVersion` from an example dataset and running it through the CLI `bids-validator` returns (among other issues):

```
        3: [ERR] The validation on this HED string returned an error. (code: 104 - HED_ERROR)
                ./dataset_description.json
                        Evidence: ERROR: [HED_SCHEMA_LOAD_FAILED] The supplied schema specification is invalid. Specification: no schema available

        Please visit https://neurostars.org/search?q=HED_ERROR for existing conversations about this issue.

        1: [WARN] You should define 'HEDVersion' for this file. If you don't provide this information, the HED validation will use the latest version available. (code: 109 - HED_VERSION_NOT_DEFINED)

        Please visit https://neurostars.org/search?q=HED_VERSION_NOT_DEFINED for existing conversations about this issue.
```

The warning message does need to be updated, but that's an issue that should be raised over at BIDS, as that's one of their messages.

**Comment by happy5214** [comment]
My comment above is mostly nonsense. Is this still an issue? (In other words, should we still be including an error if no schema spec/`HEDVersion` is passed?) If so, the BIDS warning should be deleted as redundant/incorrect (as we don't use the latest version as a default anymore).

**Comment by VisLab** [comment]
Alexander,
It should be an error if no HedVersion is passed.  We can talk about it
when we meet.
Thanks,
kay

**Comment by happy5214** [comment]
The error message on our side has been deemed desirable. The warning on the BIDS side (code 109) is somewhat redundant, but no action will be taken on it until bids-validator is finished being ported to Deno. Closing as "won't fix" for now.
