### ISSUE TITLE
Warning for missing column values does not identify

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-javascript#91]
The warning for missing column value in the BIDS validator does not say what column value is missing:

> Warning 2: [Code 108] HED_MISSING_VALUE_IN_SIDECAR
> [Click here for more information about this issue](https://neurostars.org/search?q=HED_MISSING_VALUE_IN_SIDECAR)
> 
> The json sidecar does not contain this column value as a possible key to a HED string.

The link just goes to neurostars and isn't relevant.

**Comment by happy5214** [comment]
Reopening until tests pass.
